#!/bin/bash

randomStr=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13 ; echo '')
fileName="tmp$randomStr.bash"
curl $1 -o "/var/onlinerun/$filePath"
chmod +xr /var/onlinerun/$filePath
./var/onlinerun/$filePath $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 
rm $filePath

