#!/bin/bash
#v0.0.0rc-2

randomStr=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13 ; echo '')
mkdir /var/onlinerun
filePath="/var/onlinerun/tmp$randomStr.sh"
curl $1 > $filePath
chmod +xr $filePath
$filePath "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" "$10" "$11"
rm $filePath
